# Modified by BW-Tech GmbH: automatic PR-title linting is disabled for owncloud.online plugin forks.
name: Lint PR title

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR title linting is disabled for owncloud.online plugin forks."