# Modified by BW-Tech GmbH: automatic upstream translation sync is disabled for owncloud.online plugin forks.
name: Translation Sync

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    uses: owncloud/reusable-workflows/.github/workflows/translation-sync.yml@main
    with:
      mode: old
      sub_path: l10n
    secrets:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
      TRANSLATION_APP_ID: ${{ secrets.TRANSLATION_APP_ID }}
      TRANSLATION_APP_PRIVATE_KEY: ${{ secrets.TRANSLATION_APP_PRIVATE_KEY }}